version: '3.8'
services:
  postgres:
    image: postgres:10.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    # image: /es-app
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: production
    ports:
      - '3000:3000'